### ISSUE TITLE
Unable to produce same output as eddsa-rdfc-2022 test vectors

### ISSUE THREAD

**Issue by botris** [digitalbazaar/jsonld-cli#25]
When I take the payload from [https://www.w3.org/TR/vc-di-eddsa/#example-proof-options-document](https://www.w3.org/TR/vc-di-eddsa/#example-proof-options-document) and I run `npx jsonld-cli canonize eddsa_proof.jsonld` I get a small difference compared to the expected output here [https://www.w3.org/TR/vc-di-eddsa/#example-canonical-proof-options-document](https://www.w3.org/TR/vc-di-eddsa/#example-canonical-proof-options-document)
The 3 line is different, expected:
```
_:c14n0 <https://w3id.org/security#cryptosuite> "eddsa-rdfc-2022" .
```
actual:
```
_:c14n0 <https://w3id.org/security#cryptosuite> "eddsa-rdfc-2022"^^<https://w3id.org/security#cryptosuiteString> .
```
This prevents creating the [subsequent same hash](https://www.w3.org/TR/vc-di-eddsa/#example-hash-of-canonical-proof-options-document-hex).
Not sure if there is an issue with this package, the spec or if there is an option I can pass to make it produce the expected outcome.

**Comment by dlongley** [comment]
Yes, the test vectors are out of date because of recent context updates to get things in shape in preparation for the upcoming CR (Candidate Recommendation) phase. The "actual" output in your above comment is what is correct. We have been waiting for all of the updates we expect to see to get in before regenerating the test vectors. I *think* all of the test-vector-relevant updates are in now and we hope to regenerate them at the end of this week or early next week.

**Comment by botris** [comment]
Ok thanks for that, that makes sense.

**Comment by dlongley** [comment]
This can be closed once https://github.com/w3c/vc-di-eddsa/pull/64 is merged.

**Comment by dlongley** [comment]
Test vectors have been updated, closing.
